# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---
- hosts: all

  gather_facts: no

  become: true
  become_user: root
  become_method: sudo

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

  tasks:
    - name: ceph-deploy osd create {{ host_name }}:{{ storage }}
      command: ceph-deploy osd create {{ host_name }}:{{ storage }}
      args:
        chdir: /home/cluster-ceph

    - name: Copy the contents of /home/cluster-ceph to /etc/ceph
      shell: cp /home/cluster-ceph/*.keyring /etc/ceph/

    - name: Make readable by all /home/cluster-ceph/ceph.client.admin.keyring
      file:
        path: /etc/ceph/ceph.client.admin.keyring
        mode: 0644

    - name: ceph -s
      command: ceph -s

    - name: ceph osd tree
      command: ceph osd tree

    - name: ceph-deploy mds create {{ master_host_name }}
      command: ceph-deploy mds create {{ master_host_name }}
      args:
        chdir: /home/cluster-ceph

    - name: ceph mds stat
      command: ceph mds stat

    - name: systemctl start ceph.target
      command: systemctl start ceph.target
