# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
# This playbook configure master multus cni.
---
- hosts: all
  become: true
  become_user: root
  become_method: sudo

  gather_facts: no

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

  tasks:
  - name: create the /opt/cni directory
    file: path=/opt/cni
          mode=0755
          state=directory

  - name: create the /opt/cni/bin directory
    file: path=/opt/cni/bin
          mode=0755
          state=directory

  - name: copy cni plugins
    unarchive:
      src: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
      dest: /opt/cni/bin/
      remote_src: yes

  - name: remove /home/multus
    file:
      dest: /home/multus
      state: absent
    ignore_errors: yes
 
  - name: Clone multus binary
    git:
      repo: https://github.com/AricentK8SRes/multus.git
      version: master
      dest: /home/multus
   
  - name: Copy and removing artifacts
    shell: |
      cp /home/multus/multus /opt/cni/bin/
      rm -rf /home/multus

  - name: copy cni plugins
    shell: chmod 777 /opt/cni/bin/*
