# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---
- hosts: all 
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: edit file /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ osd_ip }} {{ osd_host_name }}"
      ignore_errors: true

     - shell: rm /root/.ssh/id_rsa
       ignore_errors: true
     - shell: echo -e y|ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
       ignore_errors: true

     - shell: sshpass -p {{ passwd }} ssh-copy-id -o StrictHostKeyChecking=no {{ user_id }}@{{ osd_host_name }}
       ignore_errors: true

     - shell: sshpass -p {{ passwd }} ssh-copy-id -o StrictHostKeyChecking=no {{ user_id }}@{{ osd_host_name }}
       ignore_errors: true

    - name: ceph-deploy forgetkeys
      shell: ceph-deploy forgetkeys
      ignore_errors: true

    - name: ceph-deploy purge {{ osd_host_name }}
      shell: ceph-deploy purge {{ osd_host_name }}
      ignore_errors: true

    - name: ceph-deploy purgedata {{ osd_host_name }} 
      shell: ceph-deploy purgedata {{ osd_host_name }}
      ignore_errors: true

    - name: rm -f /etc/ceph/ceph.conf
      command: rm -f /etc/ceph/ceph.conf
      delegate_to: "{{ osd_host_name }}"
      ignore_errors: true

    - name: deleting already existing file
      file:
       state: absent
       path: /var/lib/ceph/osd
      ignore_errors: true

    - name: apt-get remove -y ceph-deploy
      shell: apt-get remove -y ceph-deploy
      ignore_errors: true

    - name: deleting already existing directory
      file:
       state: absent
       path: /home/cluster-ceph
      ignore_errors: true

    - name: wget -q -O- 'https://download.ceph.com/keys/release.asc' | apt-key add -
      shell: wget -q -O- 'https://download.ceph.com/keys/release.asc' | apt-key add -
      register: cat
    - debug: var=cat.stdout_lines

    - name: echo deb http://download.ceph.com/debian-jewel/ $(lsb_release -sc) main | tee /etc/apt/sources.list.d/ceph.list
      command: echo deb http://download.ceph.com/debian-jewel/ $(lsb_release -sc) main | tee /etc/apt/sources.list.d/ceph.list
      register: cat
    - debug: var=cat.stdout_lines

    - name: apt-get -qqy update && apt-get install -qqy ntp ceph-deploy
      shell: apt-get -qqy update && apt-get install -qqy ntp ceph-deploy

    - name: create directory cluster-ceph
      file:
       state: directory
       path: /home/cluster-ceph
       mode: 0644

    - name: ceph-deploy new {{ host_name }}
      command: ceph-deploy new {{ host_name }}
      args:
        chdir: /home/cluster-ceph
      register: cat
    - debug: var=cat.stdout_lines

    - name: edit ceph.conf file
      lineinfile:
           dest: /home/cluster-ceph/ceph.conf
           line: "osd pool default size = 1"
