#* Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---

- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - "{{ PROXY_DATA_FILE | default('') }}"
    - "{{ VARIABLE_FILE | default('') }}"
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"

  tasks:
    - name: apt install python-pip
      apt:
        name: python-pip

    - name: pip install pyOpenSSL -U
      pip:
        name: pyOpenSSL

    - name: apt-get install apt-transport-https
      apt:
        name: apt-transport-https
        state: latest

    - name: swapoff -a
      command: swapoff -a

    - name: remove apt.conf file
      file:
        dest: "{{ APT_CONF_DEST }}"
        state: absent 
    - name: Create file apt.conf 
      file:
        dest: "{{ APT_CONF_DEST }}"
        state: touch
    - name: edit apt.conf file
      lineinfile:
        dest: "{{ APT_CONF_DEST }}"
        line: '{{item}}'
      with_items:
        - 'Acquire::http::Proxy "{{ http_proxy }}";'
        - 'Acquire::https::Proxy "{{ https_proxy }}";'
        - 'Acquire::no::Proxy "{{ no_proxy }}";'
    - name: apt-get update
      apt:
        update_cache: yes 

    - name: Install remaining dependencies
      apt:
        name:
        - curl
        - sshpass
        - python-pip
        - ceph-common
        - build-essential
        - autoconf
        - libtool
        - pkg-config
        - python-opengl
        - python-imaging
        - python-pyrex 
        - python-pyside.qtopengl
        - idle-python2.7
        - qt4-dev-tools
        - qt4-designer
        - libqtgui4 
        - libqtcore4
        - libqt4-xml
        - libqt4-test
        - libqt4-script
        - libqt4-network
        - libqt4-dbus 
        - python-qt4
        - python-qt4-gl
        - libgle3
        - python-dev
        - libssl-dev
        - psmisc
        - golang

    - name: Enable root login on all nodes
      replace:
        dest: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin no'
        replace: 'PermitRootLogin yes'
        backup: yes

    - name: copying docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb 
      copy: src="{{SRC_PACKAGE_PATH}}../docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb" dest="{{APT_ARCHIVES_SRC}}" 

    - name: dpkg -i docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb
      apt:
         deb: "{{APT_ARCHIVES_SRC}}docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb"
