#* Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---

- hosts: "{{ target }}"
  become: true
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
    - "{{ VARIABLE_FILE }}"
  tasks:
    - name: change host name to "{{host_name}}"
      command: hostname "{{host_name}}"

    - name: swapoff -a
      command: swapoff -a
 
    - name: remove file /etc/hostname
      file:
        dest: /etc/hostname
        state: absent
 
    - name: create file /etc/hostname
      file:
        dest: /etc/hostname
        state: touch

    - name: edit file /etc/hostname
      lineinfile:
        dest: /etc/hostname
        line: '{{host_name}}'

    - name: remove apt.conf file
      file:
        dest: "{{ APT_CONF_DEST }}"
        state: absent 
    - name: Create file apt.conf 
      file:
        dest: "{{ APT_CONF_DEST }}"
        state: touch
    - name: edit apt.conf file
      lineinfile:
        dest: "{{ APT_CONF_DEST }}"
        line: '{{item}}'
      with_items:
        - 'Acquire::http::Proxy "{{ http_proxy }}";'
        - 'Acquire::https::Proxy "{{ https_proxy }}";'
        - 'Acquire::no::Proxy "{{ no_proxy }}";'

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common

    - name: Add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt-addrepository docker-ce
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: apt-get update
      apt:
        update_cache: yes 

    - name: Install remaining dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - sshpass
        - python-pip
        - ceph-common
        - build-essential
        - autoconf
        - libtool
        - pkg-config
        - python-opengl
        - python-imaging
        - python-pyrex 
        - python-pyside.qtopengl
        - idle-python2.7
        - qt4-dev-tools
        - qt4-designer
        - libqtgui4 
        - libqtcore4
        - libqt4-xml
        - libqt4-test
        - libqt4-script
        - libqt4-network
        - libqt4-dbus 
        - python-qt4
        - python-qt4-gl
        - libgle3
        - python-dev
        - libssl-dev
        - psmisc
        - golang
        - docker-ce

    - name: install docker repository public key
      shell: curl -k https://apt.dockerproject.org/gpg >docke_key;apt-key add docke_key
