# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---
- hosts: localhost

  gather_facts: no

  tasks:
    - name: Adding line "{{ host_name }} ansible_ssh_host={{ ip }}" to "{{ PROJ_ARTIFACT_DIR }}/inventory/inventory.cfg"
      lineinfile:
           dest: "{{ PROJ_ARTIFACT_DIR }}/inventory/inventory.cfg"
           line: "{{ host_name }} ansible_ssh_host={{ ip }} http_proxy={{ http_proxy }}"
           insertbefore: BOF

