#* Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
kubernetes:
  Project_name: My_project
  node_configuration:
    - host:
        hostname: {{ vm_1_name }}
        ip: {{ vm_1_admin_ip }}
        node_type: minion
        label_key: zone
        registry_port: 2376
        label_value: minion
        password: {{ node_host_pass }}
        user: root
  Networks:
       - Multus_network:
          - CNI:
            - sriov
            - macvlan
            - dhcp
          - CNI_Configuration:
            - Macvlan:
                  - macvlan_networks:
                        hostname: {{ vm_2_name }}
                        gateway: {{ mult_ip_prfx }}.1
                        ip: {{ vm_2_mult_ip }}
                        parent_interface: {{ mult_iface }}
#                        vlanid: 34
#                        master: enp8s0.34
                        masterplugin: True
                        network_name: {{ mult_net_name }}
                        rangeEnd: {{ mult_ip_prfx }}.60
                        rangeStart: {{ mult_ip_prfx }}.55
                        routes_dst: 0.0.0.0/0
                        subnet: {{ mult_ip_prfx }}.0/24
                        type: host-local
            - Sriov:
                  - host:
                     hostname: {{ vm_3_name }}
                     networks:
                      - network_name: {{ sriov_net_name }}
                        sriov_intf: {{ sriov_iface }}
                        rangeStart: {{ sriov_ip_prfx }}.30
                        rangeEnd: {{ sriov_ip_prfx }}.40
                        type: host-local
                        sriov_subnet: {{ sriov_ip_prfx }}.0/16
                        sriov_gateway: {{ sriov_ip_prfx }}.1
                        dpdk_enable: "no"
