---

- hosts: "{{host_name}}" 
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

  tasks:

   - name: ceph-deploy admin {{host_name}} 
     command: ceph-deploy admin {{host_name}}
     args:
       chdir: /home/cluster-ceph
     ignore_errors: true
     delegate_to: "{{master_host_name}}"

  
