---

- hosts: "{{master_host_name}}" 
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
  
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

  tasks:

   - name: sudo chmod +r /etc/ceph/ceph.client.admin.keyring 
     command: sudo chmod +r /etc/ceph/ceph.client.admin.keyring
     args:
       chdir: /home/cluster-ceph
     ignore_errors: true

   - name: ceph -s
     command: ceph -s
     ignore_errors: true

   - name: ceph osd tree
     command: ceph osd tree
     ignore_errors: true

   - name: ceph-deploy mds create {{master_host_name}}
     command: ceph-deploy mds create {{master_host_name}}
     args:
       chdir: /home/cluster-ceph
     ignore_errors: true

   - name: ceph mds stat 
     command: ceph mds stat
     args:
       chdir: /home/cluster-ceph
     ignore_errors: true

   - name: systemctl start ceph.target
     command: systemctl start ceph.target
     args:
       chdir: /home/cluster-ceph
     ignore_errors: true

  
