# This playbook delete flannel network.
---

- hosts: "{{ host_name }}"
  become: yes
  become_user: root
  tasks:
    - name: delete flannel rbac 
      command: kubectl delete -f /etc/kubernetes/kube-cni-flannel-rbac.yml 
      when: node_type == "master" 

    - name: delete flannel daemon 
      command: kubectl delete -f /etc/kubernetes/kube-cni-flannel.yml 
      when: node_type == "master" 

    - name: delete flannel interface 
      command: ip link del flannel.1 

    - name: Clean flannel conf
      file:
        state: absent
        path: /run/flannel  

    - name: flannel network deletion 
      command: kubectl delete network {{networkName}} 
      when: node_type == "master" 
