---

- hosts: localhost
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    
    - name: copy "{{PROJECT_PATH}}{{Project_name}}/k8s-cluster.yml" to "{{KARGO_PATH}}kargo/inventory/group_vars/k8s-cluster.yml" 
      copy: src="{{PROJECT_PATH}}{{Project_name}}/k8s-cluster.yml" dest="{{KARGO_PATH}}kargo/inventory/group_vars/k8s-cluster.yml"

    - name: copy copying "{{PROJECT_PATH}}{{Project_name}}/inventory.cfg" to "{{KARGO_PATH}}kargo/inventory/inventory.cfg" 
      copy: src="{{PROJECT_PATH}}{{Project_name}}/inventory.cfg" dest="{{KARGO_PATH}}kargo/inventory/inventory.cfg"

    - name: Reset/Remove kubernet cluster|logs redirect to /var/log/kubernetes_kargo.log
      shell: ansible-playbook -i inventory/inventory.cfg -u root -e ansible_ssh_user=root -b reset.yml >>/var/log/kubernetes_kargo.log 
      args:
         chdir: "{{KARGO_PATH}}kargo/"
