---

- hosts: localhost
  become: true
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
    - "{{ VARIABLE_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    - name: remove old data in  apt.conf
      file:
        dest: "{{ APT_CONF_DEST }}"
        state: absent
    - name: new file apt.conf
      file:
        dest: "{{ APT_CONF_DEST }}"
        state: touch
    - name: adding http data in apt.conf
      lineinfile:
        dest: "{{ APT_CONF_DEST }}"
        regexp: 'Acquire::http::Proxy'
        line: 'Acquire::http::Proxy "{{ http_proxy }}";'
    - name: adding https in apt.conf
      lineinfile:
        dest: "{{ APT_CONF_DEST }}"
        regexp: 'Acquire::https::Proxy'
        line: 'Acquire::https::Proxy "{{ https_proxy }}";'


