---
- hosts: localhost
  become: true
  vars_files:
#    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
 # vars:
  # host_name_map: "{{ host_name_map }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
  - name: Clean sriov  if already exeists 
    file:
       state: absent
       path: "{{SRC_PACKAGE_PATH}}/dpdk"
  - name: clonig the dpdk
    command: git clone https://github.com/emmericp/dpdk.git
    args:
       chdir: "{{SRC_PACKAGE_PATH}}"
  - name : install golang
    command: apt-get update
  - name : install golang
    command: apt-get install golang -y
