---

- hosts: all
  become: true
#  become_user: root
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
    - "{{ VARIABLE_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
   - name: Copying public keys
     copy:
       src: "/tmp/id_rsa.pub"
       dest: "/tmp/id_rsa.pub"

   - name: copy the public keys
     command: cat /tmp/id_rsa.pub
     register: id

   - debug:
      var: id.stdout
   - lineinfile:
      dest: /root/.ssh/authorized_keys
      line: "{{ id.stdout }}"
   - name: ensure file exists
     copy:
      content: ""
      dest: /root/.ssh/known_hosts
      force: no

   - name: add to known hosts
     shell: ssh-keyscan "{{ target }}" >> /root/.ssh/known_hosts
