---
- hosts: "{{host_name}}"
  become: yes
  become_user: root
  tasks:
      - stat: path=/home/{{network_name}}_file.conf
        register: file_path
      - name: deleting the created file
        file: name=/home/{{network_name}}_file.conf state=absent
        when: file_path.stat.exists == true
        ignore_errors: true
      - name: Ansible create macvlan network file as master plugin
        copy:
         dest: "/home/{{network_name}}_file.conf"
         content: |
           apiVersion: "kubernetes.com/v1"
           kind: Network
           metadata:
             name: {{network_name}}
           plugin: sriov
           args: '[
             {
                "name": "{{network_name}}",
                "type": "sriov",
                "if0": "{{intf}}",
                "ipam": {
                "type": "dhcp"
                  }
               }
             ]'

      
      
      - name : creating the sriov network as per the interface
        shell: kubectl create -f {{network_name}}_file.conf
        args:
            chdir: /home/
        register: result
      - debug:
          var: result
      - stat: path=/home/{{network_name}}_file.conf
        register: file_path
      - name: deleting the created file
        file: name=/home/{{network_name}}_file.conf state=absent
        when: file_path.stat.exists == true
      
