# This playbook delete weave conf file.
---

- hosts: "{{ host_name }}"
  become: yes
  become_user: root
  tasks:
    - name: Clean artifact path
      file:
        state: absent
        path: /etc/cni/net.d/   

    - name: create the /etc/cni directory 
      file: path=/etc/cni
            mode=0755
            state=directory
      
    - name: create the /etc/cni/net.d directory 
      file: path=/etc/cni/net.d 
            mode=0755
            state=directory
 
    - name: create multus-cni.conf file
      file: path=/root/multus-cni.conf state=touch
            mode=0644

    - name: write data in /root/multus-cni.conf file                                                                        
      blockinfile:                                                                                              
        dest: /root/multus-cni.conf
        block: |
         {
           "name": "minion-cni-network",
           "type": "multus",
           "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml",
           "delegates": [{
                 "type": "weave-net",
                 "hairpinMode": true,
                 "masterplugin": true
           }]
         }
      when: networking_plugin == "weave"
 
    - name: write data in /root/multus-cni.conf file
      blockinfile:
        dest: /root/multus-cni.conf
        block: |
         {
           "name": "minion-cni-network",
           "type": "multus",
           "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml",
           "delegates": [{
                 "type": "flannel",
                 "hairpinMode": true,
                 "masterplugin": true
           }]
         }
      when: networking_plugin == "flannel"
 
    - name: write data in /root/multus-cni.conf file
      blockinfile:
        dest: /root/multus-cni.conf
        block: |
         {
           "name": "minion-cni-network",
           "type": "multus",
           "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml"
         }
      when: networking_plugin == "none" 
    
    - name: copy multus-cni.conf in /etc/cni/net.d/ folder
      shell: cp -r /root/multus-cni.conf /etc/cni/net.d/multus-cni.conf

    - lineinfile: dest=/etc/cni/net.d/multus-cni.conf state=absent regexp="ANSIBLE MANAGED BLOCK"  

    - name: deleting created file
      file: name=/root/multus-cni.conf state=absent
      ignore_errors: true 
