---

- hosts: "{{host_name}}"
  #become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
  vars:
    storage: "{{storage_size}}"
    claim_name: "{{claim_name}}"
  tasks:
    - name: copy file basic_auth.csv to "{{host_name}}" at path "{{KUBERNETES_PATH}}"
      copy: src="{{SRC_PACKAGE_PATH}}../basic_auth.csv" dest="{{KUBERNETES_PATH}}"
    
    - name: changemod file basic_auth.csv to "{{host_name}}" at path "{{KUBERNETES_PATH}}"
      command: chmod 777 "{{KUBERNETES_PATH}}basic_auth.csv"

    - name: edit kube-apiserver.manifest
      lineinfile:
           dest: "{{KUBERNETES_PATH}}manifests/kube-apiserver.manifest"
           insertafter: '- apiserver'
           line: '    - --basic-auth-file={{KUBERNETES_PATH}}basic_auth.csv'

    - name: edit kube-apiserver.manifest
      lineinfile:
           dest: "{{KUBERNETES_PATH}}/manifests/kube-apiserver.manifest"
           regexp: '- --authorization-mode=Node,RBAC'
           line: '    - --authorization-mode=AlwaysAllow'

    - name: edit kube-apiserver.manifest
      lineinfile:
           dest: "{{KUBERNETES_PATH}}/manifests/kube-apiserver.manifest"
           regexp: '- --runtime-config=admissionregistration.k8s.io/v1alpha'
           line: '    - --runtime-config=authentication.k8s.io/v1beta1=true'

    - name: restarting api server
      command: systemctl restart kubelet 
