# This playbook create crd network.
---

- hosts: "{{ host_name }}"
  become: true
  become_user: root
  vars:
  tasks:
    - name: Get crd network
      command: kubectl get crd
      ignore_errors: true
      register : res
    - debug:
       var : res.stderr_lines

    - name: copy crdNetwork file 
      copy: src="{{SRC_PACKAGE_PATH}}../multus_cni/crdNetwork.yaml" dest=/etc/kubernetes/

    - name: Create crd network
      command: kubectl create -f /etc/kubernetes/crdNetwork.yaml
      ignore_errors: true
