# This playbook configure flannel interface at master.
---

- hosts: "{{ ip }}"
  become: true
  become_user: root
  tasks:
    - name: patch nodes 
      command: kubectl patch node {{ host_name}} -p '{"spec":{"podCIDR":"{{subnet}}"}}'
      ignore_errors: yes
