#* Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
# This playbook configure flannel interface at master.
---

- hosts: "{{ host_name }}"
  become: true
  become_user: root
  tasks:
    - name: run dos2unix on yaml file
      command: dos2unix "{{SRC_PACKAGE_PATH}}../multus_cni/flannel/kube-cni-flannel-rbac.yml"
      delegate_to: "localhost"

    - name: run dos2unix on yaml file
      command: dos2unix "{{SRC_PACKAGE_PATH}}../multus_cni/flannel/kube-cni-flannel.yml"
      delegate_to: "localhost"

    - name: update ip in flannel.yaml file 
      lineinfile:                                                                               
       dest: "{{SRC_PACKAGE_PATH}}../multus_cni/flannel/kube-cni-flannel.yml"                        
       regexp: '"Network":'                                                       
       line: '      "Network": "{{ network }}",' 
      delegate_to: "localhost"
 
    - name: copy flannel rbac 
      shell: scp -r "{{SRC_PACKAGE_PATH}}../multus_cni/flannel/kube-cni-flannel-rbac.yml" root@"{{ip}}":/etc/kubernetes/kube-cni-flannel-rbac.yml
      delegate_to: "localhost"

    - name: copy flannel rbac 
      shell: scp -r "{{SRC_PACKAGE_PATH}}../multus_cni/flannel/kube-cni-flannel.yml" root@"{{ip}}":/etc/kubernetes/kube-cni-flannel.yml
      delegate_to: "localhost"

    - name: create flannel rbac 
      command: kubectl create -f /etc/kubernetes/kube-cni-flannel-rbac.yml
      ignore_errors: true 

    - name: launch flannel daemon 
      command: kubectl create -f /etc/kubernetes/kube-cni-flannel.yml 
      ignore_errors: true 

    - name: Ansible create flannel network file
      copy:
       dest: "/home/{{ networkName }}_file.yaml"
       content: |
         apiVersion: "kubernetes.com/v1"
         kind: Network
         metadata:
          name: {{ networkName }}
         plugin: flannel
         args: '[
           {
              "delegate": {
              "isDefaultGateway":true
            }
          }
         ]'

    - name: creating flannel network
      command: "{{ item }}"
      with_items:
            - kubectl create -f /home/{{networkName}}_file.yaml
      ignore_errors: true
 
    - name: deleting created file
      file: name=/home/{{networkName}}_file.yaml state=absent
      ignore_errors: true 
