---

- hosts: localhost
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    - name: create directory "{{KARGO_PATH}}"
      file:
       state: directory	
       path: "{{KARGO_PATH}}"
       mode: 0644

    - name: Copy kargo to "{{KARGO_PATH}}" 
      copy:
         src: "{{SRC_PACKAGE_PATH}}../kargo.tar.gz"
         dest: "{{KARGO_PATH}}"
    - name: untar kargo
      shell: tar -xvzf kargo.tar.gz
      args:
         chdir: "{{KARGO_PATH}}"

    - name: copy "{{PROJECT_PATH}}{{Project_name}}/k8s-cluster.yml" to "{{KARGO_PATH}}kargo/inventory/group_vars/k8s-cluster.yml"
      copy: src="{{PROJECT_PATH}}{{Project_name}}/k8s-cluster.yml" dest="{{KARGO_PATH}}kargo/inventory/group_vars/k8s-cluster.yml"

    - name: copying "{{PROJECT_PATH}}{{Project_name}}/inventory.cfg" to "{{KARGO_PATH}}kargo/inventory/inventory.cfg" 
      copy: src="{{PROJECT_PATH}}{{Project_name}}/inventory.cfg" dest="{{KARGO_PATH}}kargo/inventory/inventory.cfg"

    - name: remove temprory inventory file
      file:
       state: absent
       path: inventory.cfg

    - name: Dynamic deployment of kubernetes node|logs redirect to /var/log/kubernetes_kargo.log
      shell: ansible-playbook -i inventory/inventory.cfg -u root -e ansible_ssh_user=root -b cluster.yml --limit "{{host_name}}" >>/var/log/kubernetes_kargo.log
      args:
         chdir: "{{KARGO_PATH}}kargo/"

