---
- hosts: "{{host_name}}"
  tasks:

  - name: Clean sriov dpdk if already exeists in /etc/cni/scripts/
    file:
       state: absent
       path: /etc/cni/scripts/
    ignore_errors: yes

  - name: supali 
    file:
       path: /etc/cni/scripts/
       state: directory
       mode: 0755    
  - name: Clean sriov dpdk if already exeists in /etc/cni/scripts/
    file:
       state: absent
       path: /etc/cni/scripts/
  - name: copy sriov file
    copy:
       src: "{{SRC_PACKAGE_PATH}}/dpdk/usertools/dpdk-devbind.py"
       dest: /etc/cni/scripts/
       mode: 777
  - name: change permission of dpdk-devbind.py
    command: chmod 777 dpdk-devbind.py
    args:
       chdir: /etc/cni/scripts/
  - name: Clean cpu_layout.py  if already exeists in /etc/cni/scripts
    file:
       state: absent
       path: /etc/cni/scripts/cpu_layout.py
  - name: copy file
    copy:
       src: "{{SRC_PACKAGE_PATH}}/dpdk/usertools/cpu_layout.py"
       dest: /etc/cni/scripts/
       mode: 777
  - name: change permission cpu_layout.py
    command: chmod 777 cpu_layout.py
    args:
       chdir: /etc/cni/scripts/
  - name: Clean dpdk-pmdinfo.py  if already exeists in /etc/cni/scripts/
    file:
       state: absent
       path: /etc/cni/scripts/dpdk-pmdinfo.py
  - name: copy file
    copy:
       src: "{{SRC_PACKAGE_PATH}}/dpdk/usertools/dpdk-pmdinfo.py"
       dest: /etc/cni/scripts/
       mode: 777
  - name: change permission sriov
    command: chmod 777 dpdk-pmdinfo.py
    args:
       chdir: /etc/cni/scripts/
  - name: Clean dpdk-setup.sh if already exeists in /etc/cni/scripts/
    file:
       state: absent
       path: /etc/cni/scripts/dpdk-setup.sh
  - name: copy file
    copy:
       src: "{{SRC_PACKAGE_PATH}}/dpdk/usertools/dpdk-setup.sh"
       dest: /etc/cni/scripts/
       mode: 777
  - name: change permission sriov
    command: chmod 777 dpdk-setup.sh
    args:
       chdir: /etc/cni/scripts/
