#* Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---

- hosts: localhost
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
  vars:
   host_name_map: "{{ host_name_map }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes 

#    - name: remove old kargo
#      file:
#       state: absent
#       path: "{{KARGO_PATH}}"
#
#    - name: create karo dir
#      file:
#       state: directory	
#       path: "{{ CURRENT_DIR }}kargo_folder"
#       mode: 0644
#    - name: set kargo path
#      lineinfile:
#        dest: "{{ VARIABLE_FILE }}"
#        regexp: 'KARGO_PATH:'
#        line: 'KARGO_PATH: "{{ CURRENT_DIR }}kargo_folder/"'

    - name: install ansible
      pip:
       name: ansible
       version: 2.3.1.0

    - name: Install kargo
      pip:
       name: kargo
       state: latest
    - name: Clone Kargo from "{{Git_branch}}" branch
      git:
        repo: https://github.com/chiraggupta06/Kubernetes_Kargo.git
        version: "{{Git_branch}}"
        dest: "{{SRC_PACKAGE_PATH}}../Kubernetes_Kargo"
      ignore_errors: true

    - name: Copy kargo.tar.gz to "{{SRC_PACKAGE_PATH}}../"  
      copy:
         src: "{{SRC_PACKAGE_PATH}}../Kubernetes_Kargo/kargo.tar.gz"
         dest: "{{SRC_PACKAGE_PATH}}../" 

    - name: create directory "{{KARGO_PATH}}"
      file:
       state: directory	
       path: "{{KARGO_PATH}}"
       mode: 0644

    - name: Copy kargo to "{{KARGO_PATH}}" 
      copy:
         src: "{{SRC_PACKAGE_PATH}}../kargo.tar.gz"
         dest: "{{KARGO_PATH}}"
    - name: untar kargo
      shell: tar -xvzf kargo.tar.gz
      args:
         chdir: "{{KARGO_PATH}}/"

    - name: copying k8s-cluster.yml to "{{ PROJECT_PATH }}{{Project_name}}"
      copy: src="{{SRC_PACKAGE_PATH}}../k8s-cluster.yml" dest="{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml"

    - name: set kube service subnet
      replace:
        dest: "{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml"
        regexp: 'kube_service_addresses:.*'
        replace: 'kube_service_addresses: {{service_subnet}} '
    - name: set kube pod subnet
      replace:
        dest: "{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml"
        regexp: 'kube_pods_subnet:.*'
        replace: 'kube_pods_subnet: {{pod_subnet}} '
    - name: set kube networking plugin
      replace:
        dest: "{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml"
        regexp: 'kube_network_plugin:.*'
        replace: 'kube_network_plugin: {{networking_plugin}} '

    - name: copying "{{ PROJECT_PATH }}{{Project_name}}/inventory.cfg" to "{{KARGO_PATH}}kargo/inventory/inventory.cfg" 
      copy: src="{{ PROJECT_PATH }}{{Project_name}}/inventory.cfg" dest="{{KARGO_PATH}}kargo/inventory/inventory.cfg"
    - name: copying "{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml" to "{{KARGO_PATH}}kargo/inventory/group_vars/k8s-cluster.yml" 
      copy: src="{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml" dest="{{KARGO_PATH}}kargo/inventory/group_vars/k8s-cluster.yml"

    - name: remove temporary inventory file
      file:
       state: absent
       path: inventory.cfg

    - name: installating kubernetes|logs redirect to /var/log/kubernetes_kargo.log 
      shell: ansible-playbook -i inventory/inventory.cfg -u root -e ansible_ssh_user=root -b cluster.yml >>/var/log/kubernetes_kargo.log 
      args:
         chdir: "{{KARGO_PATH}}kargo/"


