---
- hosts: "{{host}}"
  become: yes
  become_user: root
  tasks:
      - stat: path=/home/{{network_name}}_file.conf
        register: file_path
      - name: Deleting Ansible macvlan network file on master_hostlocal if exist
        file: name=/home/{{network_name}}_file.conf state=absent
        when: file_path.stat.exists == true
        ignore_errors: true


      - name: Ansible create macvlan network file_hostlocal
        copy:
         dest: "/home/{{network_name}}_file.conf"
         content: |
           apiVersion: "kubernetes.com/v1"
           kind: Network
           metadata:
             name: {{network_name}}
           plugin: macvlan
           args: '[
             {
                "name": "{{network_name}}",
                "type": "macvlan",
                "master": "{{interface_node}}",
                "ipam": {
                "type": "host-local",
                "subnet": "{{subnet}}",
                "rangeStart": "{{rangeStart}}",
                "rangeEnd": "{{rangeEnd}}",
                "routes": [
                 { "dst": "{{dst}}" }
                   ],
                  "gateway": "{{gateway}}"
                  }
               }
             ]'


      - name: creating macvlan networks_hostlocal
        command: "{{ item }}"
        with_items:
            - sudo kubectl create -f /home/{{network_name}}_file.conf

#      - name: Ansible Remove macvlan network file on master_hostlocal
#        file:
#          path: /home/{{network_name}}_file.conf
#          state: absent

      - stat: path=/home/{{network_name}}_file.conf
        register: file_path
      - name: Deleting Ansible created macvlan network file on master_hostlocal
        file: name=/home/{{network_name}}_file.conf state=absent
        when: file_path.stat.exists == true
        ignore_errors: true

