---
- hosts: "{{host}}"
  become: yes
  become_user: root
  tasks:
      - stat: path=/home/{{network_name}}_file.conf
        register: file_path
      - name: Deleting Ansible macvlan network file on master_dhcp if exist
        file: name=/home/{{network_name}}_file.conf state=absent
        when: file_path.stat.exists == true
        ignore_errors: true

      - name: Ansible create macvlan network file as master plugin_dhcp
        copy:
         dest: "/home/{{network_name}}_file.conf"
         content: |
           apiVersion: "kubernetes.com/v1"
           kind: Network
           metadata:
             name: {{network_name}}
           plugin: macvlan
           args: '[
             {
                "name": "{{network_name}}",
                "type": "macvlan",
                "master": "{{interface_node}}",
                "masterplugin": true,
                "ipam": {
                "type": "dhcp"
                  }
               }
             ]'


      - name: creating macvlan networks_master plugin_dhcp
        command: "{{ item }}"
        with_items:
            - sudo kubectl create -f /home/{{network_name}}_file.conf
#            - sudo ip addr add 192.168.1.121/24 dev eth0.5
 #           - sudo ip link set eth0.5 up



#      - name: Ansible Remove macvlan network file on master_dhcp
#        file:
#          path: /home/{{network_name}}_file.conf
#          state: absent

      - stat: path=/home/{{network_name}}_file.conf
        register: file_path
      - name: Deleting Ansible macvlan network file on master_dhcp
        file: name=/home/{{network_name}}_file.conf state=absent
        when: file_path.stat.exists == true
        ignore_errors: true
