--- 
- 
  become: true
  become_user: root
  hosts: "{{ host_name }}"
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks: 
    -
      shell: cp /etc/kubernetes/manifests/kube-apiserver.manifest /etc/kubernetes/manifests/kube-apiserver.manifest_bkp
      name: "backup of kube-apiserver.manifest file"



    - name: aggregation layer setup
      lineinfile:
           dest: "/etc/kubernetes/manifests/kube-apiserver.manifest"
           insertafter: '^\    - --feature-gates='
           line: "{{ item }}"
      with_items:
        - "    - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem"
        - "    - --requestheader-allowed-names=aggregator"
        - "    - --requestheader-extra-headers-prefix=X-Remote-Extra-"
        - "    - --requestheader-group-headers=X-Remote-Group"
        - "    - --requestheader-username-headers=X-Remote-User"
        - "    - --enable-aggregator-routing=true"

    - name: authoraization  setup
      lineinfile:
           dest: "/etc/kubernetes/manifests/kube-apiserver.manifest"
           regexp: '    - --authorization-mode='
           line: '    - --authorization-mode=AlwaysAllow'

    -
      file:
        mode: 420
        path: /etc/ensconse_metrics_server
        state: directory
      name: "create directory /etc/ensconse_metrics_server"

    - git:
        repo: "https://github.com/kubernetes-incubator/metrics-server.git"
        dest: /etc/ensconse_metrics_server
        version: v0.2.1
        update: no


    - name: deploy metrics server
      #command: kubectl get pods --all-namespaces
      command: kubectl create -f /etc/ensconse_metrics_server/deploy/

