--- 
- 
  become: true
  become_user: root
  hosts: "{{ host_name }}"
  tasks:

    - name: delete metrics server
      #command: kubectl get pods --all-namespaces
      command: kubectl delete -f /etc/ensconse_metrics_server/deploy/


    -
      file:
        mode: 420
        path: /etc/ensconse_metrics_server
        state: absent
      name: "delete directory /etc/ensconse_metrics_server"

    - name: metrics server flags removal from aggregation layer
      lineinfile:
           dest: "/etc/kubernetes/manifests/kube-apiserver.manifest"
           regexp: "{{ item }}"
           state: absent
      with_items:
        - "    - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem"
        - "    - --requestheader-allowed-names=aggregator"
        - "    - --requestheader-extra-headers-prefix=X-Remote-Extra-"
        - "    - --requestheader-group-headers=X-Remote-Group"
        - "    - --requestheader-username-headers=X-Remote-User"
        - "    - --enable-aggregator-routing=true"

    - name: authoraization  flag AlwaysAllow removal
      lineinfile:
           dest: "/etc/kubernetes/manifests/kube-apiserver.manifest"
           regexp: '    - --authorization-mode=AlwaysAllow'
           line: '    - --authorization-mode=Node,RBAC'