---
- hosts: kube-master
  become: true
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    - name: delete istio gateway
      shell: "kubectl delete ingress gateway -n=istio-system"
      ignore_errors: True

    - name: create ambassador-service.yaml
      blockinfile:
       create: yes
       path: /root/ambassador-service.yaml
       block: |
        ---
        apiVersion: v1
        kind: Service
        metadata:
          labels:
            service: ambassador
          name: ambassador
          annotations:
            getambassador.io/config: |
              ---
              apiVersion: ambassador/v0
              kind:  Mapping
              name:  httpbin_mapping
              prefix: /httpbin/
              service: httpbin.org:80
              host_rewrite: httpbin.org
        spec:
          type: LoadBalancer
          ports:
          - name: ambassador
            port: 80
            targetPort: 80
          selector:
            service: ambassador
    - name: apply ambassdor yaml
      command: "kubectl create clusterrolebinding kube-system-default-admin --clusterrole=cluster-admin --serviceaccount=default:default"
      ignore_errors: True
    - name: apply ambassdor yaml
      command: "kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-no-rbac.yaml"
#      when: ambassador_rbac == "no"
#    - name: apply ambassdor yaml
#      command: "kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml"
#      when: ambassador_rbac == "yes"
    - name: apply ambassdor-service.yaml
      command: "kubectl apply -f ambassador-service.yaml"
      args:
         chdir: "/root"


