---
- hosts: kube-master
  become: true
  vars_files:
    - "{{ PROXY_DATA_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
   - shell: 'curl -L -s https://api.github.com/repos/istio/istio/releases/latest | \grep tag_name | sed "s/ *\"tag_name\": *\"\(.*\)\",*/\1/"'
     register: tag
   - debug:
       var: tag.stdout_lines.0

   - name: install istio package
     shell: "curl -L https://git.io/getLatestIstio | sh -"
     args:
      chdir: "/root"
   - name: set enviroment path
     shell: "export PATH=/root/istio-{{tag.stdout_lines.0}}/bin:$PATH"

   - name: apply kubectl
     command: "kubectl apply -f install/kubernetes/istio.yaml"
     args:
        chdir: "/root/istio-{{tag.stdout_lines.0}}/"
   - debug:
       msg: "Please add to path variable:/root/istio-{{tag.stdout_lines.0}}/bin "

#   - name: remove temprory inventory file
#     delegate_to: localhost
#     file:
#      state: absent
#      path: "{{INVENTORY_PATH}}"
#     ignore_errors: True


