---
- hosts: "{{host}}"
  become: yes
  become_user: root
  tasks:
       - name: creating vlan tag interfaces
         command: "{{ item }}"
         with_items:
          - sudo vconfig add {{parentInterface}} {{vlanId}}
          - sudo ip addr add {{ip}} dev {{parentInterface}}.{{vlanId}}
          - sudo ip link set {{parentInterface}}.{{vlanId}} up

       - name: vlan tag interface persistent
         lineinfile:
           dest: /etc/network/interfaces
           line: "auto {{parentInterface}}.{{vlanId}}\niface {{parentInterface}}.{{vlanId}} inet static\naddress {{ip}}\nnetmask 255.255.255.0\nvlan-raw-device {{parentInterface}}"
